MODE: "train"
RANDOM_SEED: 2023
MODEL:
  DEVICE: "gpu"
  PRETRAIN_CHOICE: 'imagenet'
  METRIC_LOSS_TYPE: 'arcface_triplet_center'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'yes'

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  TRAIN_NAMES: ('msmt17')
  VAL_NAMES: ('market1501')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 24
  COLOR_SPACE: 'bgr'

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 70
  BASE_LR: 0.00024

  MARGIN: 6.0

  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 16

  STEPS: [9, 20, 40, 60]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 6
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 20
  EVAL_INTERVAL: 7420

  AM_S: 30.
  AM_M: 0.35
  ID_EPSILON: 0.1
  CLASSIFICATION_LOSS_WEIGHT: 1.0

  STAGE_TRANSFORMS: ["AugMix"]
  STAGE_PERIOD: [9]

TEST:
  IMS_PER_BATCH: 16
  RE_RANKING: 'no'
  WEIGHT: "path"
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'

OUTPUT_DIR: "/home/matthew/outputs/Experiment-resnet50_ibn_a-all-tricks-amsoftmax_tri_center-256x128-bs16x4-warmup10-erase0_5-labelsmooth_on-laststride1-bnneck_on-triplet_centerloss0_0005"
