MODEL:
  PRETRAIN_PATH: '/home/haoluo/.torch/models/resnet50-19c8e357.pth'


INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  TRAIN_NAMES: ('market1501')

DATALOADER:
  SAMPLER: 'softmax'
  NUM_INSTANCE: 4
  NUM_WORKERS: 24
  COLOR_SPACE: 'bgr'

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 120
  BASE_LR: 0.0004
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  ID_EPSILON: 0.1
  IMS_PER_BATCH: 16

  STEPS: [30, 55]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 5
  WARMUP_METHOD: 'linear'

  EVAL_INTERVAL: 738
  CHECKPOINT_PERIOD: 20
  LOG_PERIOD: 20
  EVAL_PERIOD: 20

TEST:
  IMS_PER_BATCH: 16

OUTPUT_DIR: "/home/haoluo/log/reid/market1501/softmax_bs64_256x128"


